# Generated by Django 4.0.1 on 2022-01-30 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('pointsFromPos', models.IntegerField(default=0)),
                ('pointsFromPick', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=4, null=True)),
                ('EstimatedRound', models.IntegerField(default=7)),
                ('EstimatedPick', models.IntegerField(default=32)),
                ('EstimatedOverAll', models.IntegerField()),
                ('college', models.CharField(max_length=256)),
                ('age', models.CharField(max_length=30)),
                ('TakenRound', models.IntegerField(null=True)),
                ('TakenPick', models.IntegerField(null=True)),
                ('TakenOverall', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('runnerUp', models.ManyToManyField(related_name='leagueRunnerUp', to='draft.Competitor')),
                ('winner', models.ManyToManyField(related_name='leagueWinner', to='draft.Competitor')),
            ],
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('pick', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.player')),
            ],
        ),
        migrations.CreateModel(
            name='CompPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('round', models.IntegerField()),
                ('pick', models.IntegerField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.competitor')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='draft.player')),
            ],
        ),
        migrations.AddField(
            model_name='competitor',
            name='league',
            field=models.ManyToManyField(to='draft.League'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
