# Generated by Django 4.0.1 on 2022-02-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comppick',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='EstimatedOverAll',
        ),
        migrations.RemoveField(
            model_name='player',
            name='TakenOverall',
        ),
        migrations.AddField(
            model_name='comppick',
            name='pos',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
