# Generated by Django 4.0.1 on 2022-02-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_remove_comppick_name_remove_player_estimatedoverall_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='EstimatedPick',
        ),
    ]
