# Generated by Django 4.0.1 on 2022-02-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_remove_player_estimatedpick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='TakenPick',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='TakenRound',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
