# Generated by Django 4.0.1 on 2022-02-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_alter_player_takenpick_alter_player_takenround'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comppick',
            name='comp',
        ),
        migrations.AlterField(
            model_name='comppick',
            name='player',
            field=models.CharField(max_length=256),
        ),
    ]
