# Generated by Django 4.0.1 on 2022-02-08 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0006_alter_comppick_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comppick',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='draft.player'),
        ),
    ]
