# Generated by Django 4.0.1 on 2022-02-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0007_alter_comppick_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='comppick',
            name='comp',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
