# Generated by Django 4.0.1 on 2022-02-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0008_comppick_comp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comppick',
            name='player',
        ),
        migrations.AddField(
            model_name='comppick',
            name='player',
            field=models.ManyToManyField(to='draft.Player'),
        ),
    ]
