# Generated by Django 4.0.1 on 2022-02-08 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0009_remove_comppick_player_comppick_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comppick',
            name='player',
        ),
        migrations.AddField(
            model_name='comppick',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='draft.player'),
        ),
    ]
