# Generated by Django 4.0.1 on 2022-02-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0011_league_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='name',
        ),
    ]
