# Generated by Django 4.0.1 on 2022-02-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0012_remove_competitor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='league',
        ),
        migrations.AddField(
            model_name='league',
            name='competitors',
            field=models.ManyToManyField(to='draft.Competitor'),
        ),
    ]
