# Generated by Django 4.0.1 on 2022-02-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0013_remove_competitor_league_league_competitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='competitors',
        ),
        migrations.AddField(
            model_name='competitor',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='draft.league'),
        ),
    ]
