# Generated by Django 4.0.1 on 2022-02-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0015_alter_competitor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='EstimatedRound',
        ),
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='col_class',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='conf',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='pos',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='suffix',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='college',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
