# Generated by Django 4.0.1 on 2022-02-14 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0016_remove_player_estimatedround_remove_player_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comppick',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.competitor'),
        ),
    ]
