# Generated by Django 4.0.1 on 2022-02-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0020_rename_takenpick_player_taken_pick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comppick',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
