# Generated by Django 4.0.1 on 2022-02-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0021_comppick_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comppick',
            old_name='correct',
            new_name='correct_player',
        ),
        migrations.AddField(
            model_name='comppick',
            name='correct_pos',
            field=models.BooleanField(default=False),
        ),
    ]
