# Generated by Django 4.0.1 on 2022-02-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0022_rename_correct_comppick_correct_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('round', models.IntegerField()),
                ('pick', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.player')),
            ],
        ),
    ]
