# Generated by Django 4.0.1 on 2022-02-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0023_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='comppick',
            name='overall',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draft',
            name='overall',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='pick',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='round',
            field=models.IntegerField(null=True),
        ),
    ]
