# Generated by Django 4.0.1 on 2022-02-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0024_comppick_overall_draft_overall_alter_draft_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DraftPick',
        ),
    ]
