# Generated by Django 4.0.1 on 2022-04-12 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0027_alter_comppick_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comppick',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.competitor'),
        ),
    ]
